{
 "title": "Mining Farm",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Rigs with issues",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "{issues=\"is_issue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({issues=\"is_issue\"}>1) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solar vs Consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum({sonoffs=\"power\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({sonoffs=\"power\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Degradation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({issues=\"is_issue\"} == 1) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rigs Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    {
     "expr": "{rigs=\"hash\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "{sonoffs=\"energy\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{sun2000=\"energy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SUM Over Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum({sonoffs=\"energy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy SUM",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({sonoffs=\"energy\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "{sonoffs=\"total_power\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "{sonoffs=\"power\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "{sonoffs=\"voltage\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage MAX",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max({sonoffs=\"voltage\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Voltage MIN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "min({sonoffs=\"voltage\"})"
    }
   ]
  },
  {
   "title": "Currencies Mined",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum({currency=\"clo\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({currency=\"nexa\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phase Sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 26 },
   "targets": [
    {
     "expr": "sum({phaseP=\"1\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({phaseP=\"2\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum({phaseP=\"hs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({phaseP=\"1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({phaseP=\"2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PH house",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({phaseP=\"hs\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}